<a href="https://colab.research.google.com/github/Balu-srm23/Machine-Learning/blob/main/Lab_AP23110011409.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🧑‍💻 NumPy Complete Guided Project
**Instructor / Student Colab Notebook** – covers *all* key concepts from `Numpy‑1` to `Numpy‑5`.

*Generated: 08 Aug 2025*


**Table of Contents**

1. [Setup](#setup)  
2. [Array Creation & Dtypes](#creation)  
3. [Array Attributes & Inspection](#attributes)  
4. [Indexing, Slicing, Fancy Indexing](#indexing)  
5. [Reshaping, Transpose & Copies vs Views](#reshape)  
6. [Joining, Splitting, Set & Sorting Ops](#join)  
7. [Arithmetic Ops, Universal Functions](#arithmetic)  
8. [Broadcasting (Rules + Examples)](#broadcast)  
9. [Statistics & Aggregations](#stats)  
10. [Random Numbers & Reproducibility](#random)  
11. [Structured / Recarrays](#structured)  
12. [Linear Algebra Essentials](#linalg)  
13. [File I/O (`npy`, `npz`, `txt`)](#io)  
14. [Datetime64 & Timedelta64](#datetime)  
15. [Masked Arrays & NaNs](#mask)  
16. [Mini‑Project — Fitness Data Analysis](#project)  
17. [Conclusion & Next Steps](#conclusion)  


## <a name='setup'></a>1️⃣ Setup

In [3]:
import numpy as np, math, os, pathlib, types, textwrap, random
print('NumPy version:', np.__version__)

NumPy version: 2.0.2


## <a name='creation'></a>2️⃣ Array Creation & Dtypes

Key functions: `np.array`, `np.arange`, `np.linspace`, `zeros`, `ones`, `full`, `eye`, `identity`, `diag`, `empty`

In [4]:
# EXAMPLE
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr2 = np.linspace(0, 1, 6)
arr3 = np.full((2,3), 7.5)
print(arr1, arr2, arr3, sep="\n")
print("dtypes:", arr1.dtype, arr2.dtype)


[1 2 3]
[0.  0.2 0.4 0.6 0.8 1. ]
[[7.5 7.5 7.5]
 [7.5 7.5 7.5]]
dtypes: int32 float64


In [5]:
# 🖊️ TODO: create a 10×10 chessboard pattern using zeros & ones

a2=np.full((10,10),0)
a2[0::2,0::2]=1
a2[1::2,1::2]=1
print(a2)

[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


## <a name='attributes'></a>3️⃣ Array Attributes & Inspection

`shape`, `ndim`, `size`, `dtype`, `itemsize`, `nbytes`

In [6]:
M = np.arange(12).reshape(3,4)
print('shape', M.shape, 'ndim', M.ndim, 'size', M.size, 'itemsize', M.itemsize, 'total bytes', M.nbytes)


shape (3, 4) ndim 2 size 12 itemsize 8 total bytes 96


In [7]:
# 🖊️ TODO: check memory footprint of a 1000×1000 float64 array
m=np.full((1000,1000), 0)
print('total memory: ',m.nbytes,' bytes')

total memory:  8000000  bytes


## <a name='indexing'></a>4️⃣ Indexing, Slicing & Fancy Indexing

In [8]:
a = np.arange(1,26).reshape(5,5)
print(a[:, 0])     # first column
print(a[::2, ::2]) # every 2nd row/col
mask = (a % 3 == 0)
print('multiples of 3:', a[mask])


[ 1  6 11 16 21]
[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
multiples of 3: [ 3  6  9 12 15 18 21 24]


In [9]:
# 🖊️ TODO: use fancy indexing to swap first and last rows of `a`
a = np.arange(16).reshape(4, 4)
print("Original:\n", a)
a[[0, -1]] = a[[-1, 0]]
print("After swapping first and last rows:\n", a)

Original:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After swapping first and last rows:
 [[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


## <a name='reshape'></a>5️⃣ Reshaping, Transpose & Copies vs Views

In [10]:
b = np.arange(8)
B = b.reshape(2,4)
B[0,0] = 99
print('b is modified:', b)
C = b.reshape(2,4).copy()
C[0,0] = -1
print('b unchanged with copy:', b)


b is modified: [99  1  2  3  4  5  6  7]
b unchanged with copy: [99  1  2  3  4  5  6  7]


In [11]:
# 🖊️ TODO: Flatten a 3‑D array into 1‑D using both `ravel` and `flatten`; observe copy vs view.
import numpy as np

a = np.arange(8).reshape(2, 2, 2)
print("Original 3D array:\n", a)

r = a.ravel()
print("\nFlattened using ravel():", r)

f = a.flatten()
print("\nFlattened using flatten():", f)

a[0, 0, 0] = 999

print("\nModified original array:\n", a)
print("\nAfter modifying original:")
print("ravel view reflects change:", r)
print("flatten copy unchanged:", f)


Original 3D array:
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]

Flattened using ravel(): [0 1 2 3 4 5 6 7]

Flattened using flatten(): [0 1 2 3 4 5 6 7]

Modified original array:
 [[[999   1]
  [  2   3]]

 [[  4   5]
  [  6   7]]]

After modifying original:
ravel view reflects change: [999   1   2   3   4   5   6   7]
flatten copy unchanged: [0 1 2 3 4 5 6 7]


## <a name='join'></a>6️⃣ Joining, Splitting, Set & Sorting Ops

In [12]:
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
print('union', np.union1d(x,y))
print('intersect', np.intersect1d(xy,[1,2,10]))
print('sorted descending', np.sort(xy)[::-1])


union [1 2 3 4 5 6]
intersect [1 2]
sorted descending [6 5 4 3 2 1]


In [13]:
# 🖊️ TODO: split `xy` back into two equal halves using `np.array_split`
x = np.array([1,3,5]); y = np.array([2,4,6])
xy = np.concatenate([x,y])
split_xy = np.array_split(xy, 2)
print(split_xy[0])
print(split_xy[1])


[1 3 5]
[2 4 6]


## <a name='arithmetic'></a>7️⃣ Arithmetic Ops & Universal Functions

In [14]:
v = np.arange(5)
print('exp', np.exp(v))
print('sin', np.sin(v))
print('vectorised addition', v + 10)


exp [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
sin [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
vectorised addition [10 11 12 13 14]


In [15]:
# 🖊️ TODO: given degrees [0,30,45,60,90], compute radians and sin values.
degrees = np.array([0, 30, 45, 60, 90])
radians = np.deg2rad(degrees)
sin_values = np.sin(radians)
print(radians)
print(sin_values)


[0.         0.52359878 0.78539816 1.04719755 1.57079633]
[0.         0.5        0.70710678 0.8660254  1.        ]


## <a name='broadcast'></a>8️⃣ Broadcasting Rules

Rules: compare dimensions from right → left; stretch size 1 dims; mismatch error.

In [16]:
row = np.arange(5)
col = np.arange(3).reshape(3,1)
matrix = row + col  # broadcast to 3×5
print(matrix)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]]


In [17]:
# 🖊️ TODO: use broadcasting to create a 10×10 multiplication table.
row = np.arange(1, 11)
col = np.arange(1, 11).reshape(10, 1)
multiplication_table = row * col
print(multiplication_table)


[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


## <a name='stats'></a>9️⃣ Statistics & Aggregations

In [18]:
data = np.random.default_rng(0).integers(1, 100, size=(5,4))
print('data\n', data)
print('row sums', data.sum(axis=1))
print('col means', data.mean(axis=0))


data
 [[85 64 51 27]
 [31  5  8  2]
 [18 81 65 91]
 [50 61 97 73]
 [63 54 56 93]]
row sums [227  46 255 281 266]
col means [49.4 53.  55.4 57.2]


In [19]:
# 🖊️ TODO: compute np.percentile (25th, 50th, 75th) of flattened data.
percentiles = np.percentile(data, [25, 50, 75])
print(percentiles)


[30.  58.5 75. ]


## <a name='random'></a>🔟 Random Numbers & Reproducibility

In [20]:
rng = np.random.default_rng(42)
rand_floats = rng.random(5)
rand_ints = rng.integers(low=10, high=50, size=5)
print(rand_floats, rand_ints)
rng2 = np.random.default_rng(42)
assert np.allclose(rand_floats, rng2.random(5))


[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735] [31 49 39 40 38]


In [21]:
# 🖊️ TODO: simulate rolling a fair six‑sided die 100 times; estimate proportion of 6s.
rng = np.random.default_rng(42)
rolls = rng.integers(1, 7, size=100)
proportion_of_sixes = np.mean(rolls == 6)
print(proportion_of_sixes)


0.14


## <a name='structured'></a>1️⃣1️⃣ Structured / Record Arrays

In [22]:
people = np.array([('Alice', 25, 55.0), ('Bob', 30, 85.5)],
                   dtype=[('name','U10'), ('age','i4'), ('weight','f4')])
print(people['name'], people['age'].mean())


['Alice' 'Bob'] 27.5


In [23]:
# 🖊️ TODO: add a new field 'height' to the structured array using `np.lib.recfunctions.append_fields` (hint: pip install?).
from numpy.lib import recfunctions as rfn

heights = [160.0, 175.5]
people_extended = rfn.append_fields(people, 'height', heights, dtypes='f4', usemask=False)
print(people_extended)


[('Alice', 25, 55. , 160. ) ('Bob', 30, 85.5, 175.5)]


## <a name='linalg'></a>1️⃣2️⃣ Linear Algebra Essentials

In [24]:
A = np.random.random((3,3))
b = np.random.random(3)
x = np.linalg.solve(A, b)
print('A·x ≈ b?', np.allclose(A.dot(x), b))


A·x ≈ b? True


In [25]:
# 🖊️ TODO: compute eigenvalues of `A` using `np.linalg.eig`.
eigenvalues, _ = np.linalg.eig(A)
print(eigenvalues)


[ 2.08149417  0.29573787 -0.24828455]


## <a name='io'></a>1️⃣3️⃣ File I/O (`npy`, `npz`, `txt`)

In [26]:
np.save('array.npy', A)
loaded = np.load('array.npy')
print('loaded equals A?', np.allclose(loaded, A))
np.savez('multi_arrays.npz', A=A, b=b)


loaded equals A? True


In [27]:
# 🖊️ TODO: Use `np.savetxt` to write `data` (from stats section) to CSV then reload with `np.loadtxt`.
np.savetxt('data.csv', data, delimiter=',', fmt='%d')
loaded_data = np.loadtxt('data.csv', delimiter=',', dtype=int)
print(np.allclose(data, loaded_data))


True


## <a name='datetime'></a>1️⃣4️⃣ Datetime64 & Timedelta64

In [28]:
dates = np.arange('2023-01', '2023-04', dtype='datetime64[D]')
delta = dates[1:] - dates[:-1]
print(dates[:5], delta[0])


['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'] 1 days


In [29]:
# 🖊️ TODO: find how many Mondays appear in `dates` array.
mondays = np.sum(dates.astype('datetime64[W]').astype('int') % 7 == 0)
print(mondays)


11


## <a name='mask'></a>1️⃣5️⃣ Masked Arrays & NaNs

In [30]:
arr = np.array([1, 2, np.nan, 4, np.nan])
masked = np.ma.masked_invalid(arr)
print(masked.mean())


2.3333333333333335


In [31]:
# 🖊️ TODO: replace NaNs with column means in a 2‑D array containing NaNs.
arr2d = np.array([[1, 2, np.nan], [4, np.nan, 6], [7, 8, 9]])
col_means = np.nanmean(arr2d, axis=0)
inds = np.isnan(arr2d)
arr2d[inds] = np.take(col_means, np.where(inds)[1])
print(arr2d)


[[1.  2.  7.5]
 [4.  5.  6. ]
 [7.  8.  9. ]]


## <a name='project'></a>1️⃣6️⃣ Mini‑Project: Fitness Data Analysis

Load `fitness.txt` (tab‑separated) then follow prompts.

In [34]:
#  fitness.txt file for demonstration
dummy_data = """date\tsteps\tsleep\tmood
2023-01-01\t5000\t7\tGood
2023-01-02\t6000\t8\tGreat
2023-01-03\t4000\t6\tOkay
2023-01-04\t7000\t7\tGood
2023-01-05\t5500\t7.5\tGreat
"""

with open('fitness.txt', 'w') as f:
    f.write(dummy_data)

print("Created dummy 'fitness.txt'")

Created dummy 'fitness.txt'


In [32]:
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)
print('columns:', fitness.dtype.names, 'rows:', len(fitness))


columns: ('date', 'steps', 'sleep', 'mood') rows: 5


In [36]:
import numpy as np

# Load the data
fitness = np.genfromtxt('fitness.txt', delimiter='\t', dtype=None, encoding=None, names=True)

# Extract columns
dates = np.array(fitness['date'], dtype='datetime64[D]')
steps = np.array(fitness['steps'], dtype=int)
sleep = np.array(fitness['sleep'], dtype=float)
mood_str = np.array(fitness['mood'])

# Convert mood to numeric scale
mood_map = {'Bad': 1, 'Okay': 2, 'Good': 3, 'Great': 4}
mood = np.array([mood_map.get(m, 0) for m in mood_str])

# --- Monthly step count ---
months = dates.astype('datetime64[M]')
unique_months = np.unique(months)
monthly_steps = [np.sum(steps[months == m]) for m in unique_months]
print('Monthly Steps:', dict(zip(unique_months.astype(str), monthly_steps)))

# --- Sleep vs Mood Correlation ---
if len(np.unique(mood)) > 1:
    correlation = np.corrcoef(sleep, mood)[0, 1]
    print('Sleep vs Mood Correlation:', correlation)
else:
    print('Not enough mood variety for correlation.')

# --- Weekly average steps ---
weeks = dates.astype('datetime64[W]')
unique_weeks = np.unique(weeks)
weekly_avg_steps = [np.mean(steps[weeks == w]) for w in unique_weeks]
print('Weekly Avg Steps:', dict(zip(unique_weeks.astype(str), weekly_avg_steps)))


Monthly Steps: {np.str_('2023-01'): np.int64(27500)}
Sleep vs Mood Correlation: 0.9669875568304566
Weekly Avg Steps: {np.str_('2022-12-29'): np.float64(5500.0), np.str_('2023-01-05'): np.float64(5500.0)}


## <a name='conclusion'></a>1️⃣7️⃣ Conclusion & Further Practice
Congrats on covering **all core NumPy topics** from your five lecture notebooks!

*Keep experimenting, read the official docs, and try converting your NumPy pipelines into Pandas or JAX for more fun.*